using System.Text;

namespace ScopeARJobApplication.ConsoleShape
{
    /// <summary>
    /// Creates a Ascii ChrismasTree shape, where x's grow by 2 every line. Shape is generated by construction.
    /// </summary>
    public class ChristmasTreeShape : IConsoleShape
    {
        private readonly int Size;
        private string Shape;

        /// <summary>
        /// Create a christmas tree shape. Use GetShape() to Access.
        /// </summary>
        /// <param name="size">Horizaontal length of tree</param>
        public ChristmasTreeShape(int size)
        {
            Size = size;
            BuildShape();
        }

        private void BuildShape()
        {
            int spaceCount = Size -1;
            int xCount = 1;

            //faster for large numbers then regular string
            StringBuilder stringBuilder = new StringBuilder("");

            for (int lineNo = 0; lineNo < Size; lineNo++)
            {
                if (lineNo > 0)
                {
                    stringBuilder.Append("\n");
                }

                stringBuilder.Append(BuildLine(xCount, spaceCount));
                xCount += 2;
                spaceCount -= 1;
            }

            Shape = stringBuilder.ToString();
        }

  
        private string BuildLine(int xCount, int spaceCount)
        {
            var spaceCharacters = new string(' ', spaceCount);
            return string.Concat(spaceCharacters, new string('x', xCount), spaceCharacters);
        }

        public string GetShape()
        {
            return Shape;
        }

    }
}
