using System.Linq;
using System.Text;

namespace ScopeARJobApplication.ConsoleShape
{
    /// <summary>
    /// Creates a shape with and X pattern formed by 'x'. Shape is generated by constructor. 
    /// </summary>
    public class XShape : IConsoleShape
    {
        private readonly int Size;
        private string Shape;
        /// <summary>
        /// Create a new X pattern. Shape is generated in construtor
        /// </summary>
        /// <param name="size">This will be the width, and height of the shape.</param>
        public XShape(int size)
        {
            Size = size;
            BuildShape();
        }

        private void BuildShape()
        {
            //faster for large numbers then regular string
            StringBuilder stringBuilder = new StringBuilder(""); 

            for (int lineNo = 0; lineNo < Size; lineNo++)
            {
                if (lineNo > 0)
                {
                    stringBuilder.Append("\n");
                }

                stringBuilder.Append(BuildLine(lineNo));
            }
            Shape = stringBuilder.ToString();
        }

        private string BuildLine(int lineNo)
        {
            var lineArray = Enumerable.Repeat(" ", Size).ToArray();
            lineArray[lineNo] = "x";
            lineArray[Size - 1 - lineNo] = "x";
            return string.Concat(lineArray);
        }

        public string GetShape()
        {
            return Shape;
        }
    }
}
